"""Everything the program says, in English, German, French, Italian and Spanish.

Copyright (c) 2026 Simon Eckmiller. MIT License.
"""
from __future__ import annotations

import locale
import os
import subprocess

LANGUAGES = ("en", "de", "fr", "it", "es")

TEXTS = {
    "en": {
        "started": "Mind the Limit {version} started. Box {device}, every {interval} s, night {night} at {night_pct}%, Home Assistant: {ha}.",
        "connected": "Box connected.",
        "values": "Session {session} | week {week} | {model}",
        "unavailable": "Limits not readable ({reason}). The box shows a red {symbol}.",
        "unavailable_kept": "Limits not readable ({reason}); the values from {minutes} min ago are kept, next try in {seconds} s.",
        "device_lost": "Box not reachable: {error}. Next try in {seconds} s.",
        "brightness": "Brightness {pct}% ({why}).",
        "why_dark": "Home Assistant: {entity} is {state}",
        "why_night": "night",
        "why_day": "day",
        "yes": "yes",
        "no": "no",
        "no_device": "No box set yet. Find its address with `mind-the-limit find`, then run `mind-the-limit set device <address>`.",
        "not_macos": "Mind the Limit needs macOS (Bluetooth through IOBluetooth).",
        "no_python": "No Python 3.10 or later found. Install one (for example `brew install python`) or pass `--python <path>`.",
        "installing": "Installing into {path} …",
        "installed": "Installed. Background job {label} {state}.",
        "agent_started": "started",
        "agent_waiting": "set up, starts as soon as a box is set",
        "set_done": "{key} = {value}",
        "set_invalid": "Not a valid value for {key}: {value}",
        "status_agent": "Background job: {state}",
        "status_running": "running",
        "status_stopped": "not running",
        "status_last": "Last reading {time}: {values}",
        "status_error": "Last problem {time}: {error}",
        "status_none": "No reading yet.",
        "preview_written": "Preview written: {path}",
        "find_none": "No paired Bluetooth devices. Pair the box in System Settings → Bluetooth first.",
        "uninstalled": "Background job stopped; program and settings moved to the Trash: {path}",
        "ha_intro": "Connect Home Assistant. The panel turns dark while an entity you choose is in a state such as off or not_home.",
        "ha_url": "Home Assistant address [{default}]: ",
        "ha_unreachable": "No Home Assistant answers at {url}.",
        "ha_browser": "Your browser opens {url}. Under “Long-lived access tokens”, create a token named “Mind the Limit”, copy it and come back.",
        "ha_token": "Paste the token (the input stays hidden): ",
        "ha_rejected": "Home Assistant did not accept this token.",
        "ha_entity": "Entity that turns the panel dark, e.g. binary_sensor.lights_on or person.you: ",
        "ha_entity_unknown": "Home Assistant does not know {entity}.",
        "ha_saved": "Saved. Token in the keychain, entity {entity}.",
        "ha_forgotten": "Token removed from the keychain; Home Assistant is no longer asked.",
        "ha_env_missing": "Environment variable {name} is empty.",
    },
    "de": {
        "started": "Mind the Limit {version} gestartet. Box {device}, alle {interval} s, Nacht {night} mit {night_pct} %, Home Assistant: {ha}.",
        "connected": "Box verbunden.",
        "values": "Session {session} | Woche {week} | {model}",
        "unavailable": "Limits nicht lesbar ({reason}). Die Box zeigt ein rotes {symbol}.",
        "unavailable_kept": "Limits nicht lesbar ({reason}); die Werte von vor {minutes} min bleiben stehen, nächster Versuch in {seconds} s.",
        "device_lost": "Box nicht erreichbar: {error}. Nächster Versuch in {seconds} s.",
        "brightness": "Helligkeit {pct} % ({why}).",
        "why_dark": "Home Assistant: {entity} ist {state}",
        "why_night": "Nacht",
        "why_day": "Tag",
        "yes": "ja",
        "no": "nein",
        "no_device": "Noch keine Box eingestellt. Adresse mit `mind-the-limit find` suchen, dann `mind-the-limit set device <Adresse>`.",
        "not_macos": "Mind the Limit braucht macOS (Bluetooth über IOBluetooth).",
        "no_python": "Kein Python 3.10 oder neuer gefunden. Eines installieren (zum Beispiel `brew install python`) oder `--python <Pfad>` angeben.",
        "installing": "Installiere nach {path} …",
        "installed": "Installiert. Hintergrunddienst {label} {state}.",
        "agent_started": "gestartet",
        "agent_waiting": "eingerichtet, startet, sobald eine Box eingestellt ist",
        "set_done": "{key} = {value}",
        "set_invalid": "Kein gültiger Wert für {key}: {value}",
        "status_agent": "Hintergrunddienst: {state}",
        "status_running": "läuft",
        "status_stopped": "läuft nicht",
        "status_last": "Letzte Messung {time}: {values}",
        "status_error": "Letztes Problem {time}: {error}",
        "status_none": "Noch keine Messung.",
        "preview_written": "Vorschau geschrieben: {path}",
        "find_none": "Keine gekoppelten Bluetooth-Geräte. Die Box zuerst unter Systemeinstellungen → Bluetooth koppeln.",
        "uninstalled": "Hintergrunddienst gestoppt; Programm und Einstellungen liegen im Papierkorb: {path}",
        "ha_intro": "Home Assistant verbinden. Das Display wird dunkel, solange eine Entität deiner Wahl einen Zustand wie off oder not_home hat.",
        "ha_url": "Adresse von Home Assistant [{default}]: ",
        "ha_unreachable": "Unter {url} antwortet kein Home Assistant.",
        "ha_browser": "Dein Browser öffnet {url}. Unter „Langlebige Zugriffstoken“ einen Token „Mind the Limit“ erstellen, kopieren und hierher zurückkommen.",
        "ha_token": "Token einfügen (die Eingabe bleibt unsichtbar): ",
        "ha_rejected": "Home Assistant hat diesen Token nicht angenommen.",
        "ha_entity": "Entität, die das Display dunkel schaltet, z. B. binary_sensor.licht_an oder person.du: ",
        "ha_entity_unknown": "Home Assistant kennt {entity} nicht.",
        "ha_saved": "Gespeichert. Token im Schlüsselbund, Entität {entity}.",
        "ha_forgotten": "Token aus dem Schlüsselbund entfernt; Home Assistant wird nicht mehr gefragt.",
        "ha_env_missing": "Umgebungsvariable {name} ist leer.",
    },
    "fr": {
        "started": "Mind the Limit {version} démarré. Boîtier {device}, toutes les {interval} s, nuit {night} à {night_pct} %, Home Assistant : {ha}.",
        "connected": "Boîtier connecté.",
        "values": "Session {session} | semaine {week} | {model}",
        "unavailable": "Limites illisibles ({reason}). Le boîtier affiche un {symbol} rouge.",
        "unavailable_kept": "Limites illisibles ({reason}) ; les valeurs d'il y a {minutes} min restent affichées, nouvel essai dans {seconds} s.",
        "device_lost": "Boîtier injoignable : {error}. Nouvel essai dans {seconds} s.",
        "brightness": "Luminosité {pct} % ({why}).",
        "why_dark": "Home Assistant : {entity} est {state}",
        "why_night": "nuit",
        "why_day": "jour",
        "yes": "oui",
        "no": "non",
        "no_device": "Aucun boîtier configuré. Trouvez son adresse avec `mind-the-limit find`, puis lancez `mind-the-limit set device <adresse>`.",
        "not_macos": "Mind the Limit nécessite macOS (Bluetooth via IOBluetooth).",
        "no_python": "Aucun Python 3.10 ou plus récent trouvé. Installez-en un (par exemple `brew install python`) ou indiquez `--python <chemin>`.",
        "installing": "Installation dans {path} …",
        "installed": "Installé. Tâche de fond {label} {state}.",
        "agent_started": "démarrée",
        "agent_waiting": "configurée, démarre dès qu'un boîtier est défini",
        "set_done": "{key} = {value}",
        "set_invalid": "Valeur non valide pour {key} : {value}",
        "status_agent": "Tâche de fond : {state}",
        "status_running": "en cours",
        "status_stopped": "arrêtée",
        "status_last": "Dernière lecture {time} : {values}",
        "status_error": "Dernier problème {time} : {error}",
        "status_none": "Aucune lecture pour l'instant.",
        "preview_written": "Aperçu enregistré : {path}",
        "find_none": "Aucun appareil Bluetooth jumelé. Jumelez d'abord le boîtier dans Réglages Système → Bluetooth.",
        "uninstalled": "Tâche de fond arrêtée ; programme et réglages déplacés dans la corbeille : {path}",
        "ha_intro": "Connecter Home Assistant. L'écran s'éteint tant qu'une entité de votre choix est dans un état comme off ou not_home.",
        "ha_url": "Adresse de Home Assistant [{default}] : ",
        "ha_unreachable": "Aucun Home Assistant ne répond à {url}.",
        "ha_browser": "Votre navigateur ouvre {url}. Sous « Jetons d'accès longue durée », créez un jeton « Mind the Limit », copiez-le et revenez ici.",
        "ha_token": "Collez le jeton (la saisie reste masquée) : ",
        "ha_rejected": "Home Assistant n'a pas accepté ce jeton.",
        "ha_entity": "Entité qui éteint l'écran, p. ex. binary_sensor.lumieres ou person.vous : ",
        "ha_entity_unknown": "Home Assistant ne connaît pas {entity}.",
        "ha_saved": "Enregistré. Jeton dans le trousseau, entité {entity}.",
        "ha_forgotten": "Jeton retiré du trousseau ; Home Assistant n'est plus interrogé.",
        "ha_env_missing": "La variable d'environnement {name} est vide.",
    },
    "it": {
        "started": "Mind the Limit {version} avviato. Box {device}, ogni {interval} s, notte {night} al {night_pct}%, Home Assistant: {ha}.",
        "connected": "Box collegato.",
        "values": "Sessione {session} | settimana {week} | {model}",
        "unavailable": "Limiti non leggibili ({reason}). Il box mostra un {symbol} rosso.",
        "unavailable_kept": "Limiti non leggibili ({reason}); restano i valori di {minutes} min fa, nuovo tentativo tra {seconds} s.",
        "device_lost": "Box non raggiungibile: {error}. Nuovo tentativo tra {seconds} s.",
        "brightness": "Luminosità {pct}% ({why}).",
        "why_dark": "Home Assistant: {entity} è {state}",
        "why_night": "notte",
        "why_day": "giorno",
        "yes": "sì",
        "no": "no",
        "no_device": "Nessun box impostato. Trova l'indirizzo con `mind-the-limit find`, poi esegui `mind-the-limit set device <indirizzo>`.",
        "not_macos": "Mind the Limit richiede macOS (Bluetooth tramite IOBluetooth).",
        "no_python": "Nessun Python 3.10 o successivo trovato. Installane uno (ad esempio `brew install python`) o indica `--python <percorso>`.",
        "installing": "Installazione in {path} …",
        "installed": "Installato. Servizio in background {label} {state}.",
        "agent_started": "avviato",
        "agent_waiting": "configurato, parte appena è impostato un box",
        "set_done": "{key} = {value}",
        "set_invalid": "Valore non valido per {key}: {value}",
        "status_agent": "Servizio in background: {state}",
        "status_running": "in esecuzione",
        "status_stopped": "fermo",
        "status_last": "Ultima lettura {time}: {values}",
        "status_error": "Ultimo problema {time}: {error}",
        "status_none": "Ancora nessuna lettura.",
        "preview_written": "Anteprima salvata: {path}",
        "find_none": "Nessun dispositivo Bluetooth abbinato. Abbina prima il box in Impostazioni di Sistema → Bluetooth.",
        "uninstalled": "Servizio fermato; programma e impostazioni spostati nel Cestino: {path}",
        "ha_intro": "Collega Home Assistant. Lo schermo si spegne finché un'entità a tua scelta è in uno stato come off o not_home.",
        "ha_url": "Indirizzo di Home Assistant [{default}]: ",
        "ha_unreachable": "Nessun Home Assistant risponde su {url}.",
        "ha_browser": "Il browser apre {url}. In «Token di accesso a lungo termine» crea un token «Mind the Limit», copialo e torna qui.",
        "ha_token": "Incolla il token (l'inserimento resta nascosto): ",
        "ha_rejected": "Home Assistant non ha accettato questo token.",
        "ha_entity": "Entità che spegne lo schermo, ad es. binary_sensor.luci_accese o person.tu: ",
        "ha_entity_unknown": "Home Assistant non conosce {entity}.",
        "ha_saved": "Salvato. Token nel portachiavi, entità {entity}.",
        "ha_forgotten": "Token rimosso dal portachiavi; Home Assistant non viene più interrogato.",
        "ha_env_missing": "La variabile d'ambiente {name} è vuota.",
    },
    "es": {
        "started": "Mind the Limit {version} iniciado. Caja {device}, cada {interval} s, noche {night} al {night_pct} %, Home Assistant: {ha}.",
        "connected": "Caja conectada.",
        "values": "Sesión {session} | semana {week} | {model}",
        "unavailable": "Límites no legibles ({reason}). La caja muestra un {symbol} rojo.",
        "unavailable_kept": "Límites no legibles ({reason}); se mantienen los valores de hace {minutes} min, nuevo intento en {seconds} s.",
        "device_lost": "Caja no alcanzable: {error}. Nuevo intento en {seconds} s.",
        "brightness": "Brillo {pct} % ({why}).",
        "why_dark": "Home Assistant: {entity} está {state}",
        "why_night": "noche",
        "why_day": "día",
        "yes": "sí",
        "no": "no",
        "no_device": "Todavía no hay caja configurada. Busca su dirección con `mind-the-limit find` y ejecuta `mind-the-limit set device <dirección>`.",
        "not_macos": "Mind the Limit necesita macOS (Bluetooth mediante IOBluetooth).",
        "no_python": "No se encontró Python 3.10 o posterior. Instala uno (por ejemplo `brew install python`) o indica `--python <ruta>`.",
        "installing": "Instalando en {path} …",
        "installed": "Instalado. Tarea en segundo plano {label} {state}.",
        "agent_started": "iniciada",
        "agent_waiting": "configurada, arranca en cuanto haya una caja definida",
        "set_done": "{key} = {value}",
        "set_invalid": "Valor no válido para {key}: {value}",
        "status_agent": "Tarea en segundo plano: {state}",
        "status_running": "en marcha",
        "status_stopped": "detenida",
        "status_last": "Última lectura {time}: {values}",
        "status_error": "Último problema {time}: {error}",
        "status_none": "Todavía no hay lecturas.",
        "preview_written": "Vista previa guardada: {path}",
        "find_none": "No hay dispositivos Bluetooth emparejados. Empareja primero la caja en Ajustes del Sistema → Bluetooth.",
        "uninstalled": "Tarea detenida; programa y ajustes movidos a la Papelera: {path}",
        "ha_intro": "Conectar Home Assistant. La pantalla se apaga mientras una entidad que elijas esté en un estado como off o not_home.",
        "ha_url": "Dirección de Home Assistant [{default}]: ",
        "ha_unreachable": "Ningún Home Assistant responde en {url}.",
        "ha_browser": "Tu navegador abre {url}. En «Tokens de acceso de larga duración» crea un token «Mind the Limit», cópialo y vuelve aquí.",
        "ha_token": "Pega el token (la entrada queda oculta): ",
        "ha_rejected": "Home Assistant no aceptó este token.",
        "ha_entity": "Entidad que apaga la pantalla, p. ej. binary_sensor.luces o person.tu: ",
        "ha_entity_unknown": "Home Assistant no conoce {entity}.",
        "ha_saved": "Guardado. Token en el llavero, entidad {entity}.",
        "ha_forgotten": "Token eliminado del llavero; ya no se consulta Home Assistant.",
        "ha_env_missing": "La variable de entorno {name} está vacía.",
    },
}


def detect(run=subprocess.run, env=None) -> str:
    """The user's language: LANG/LC_ALL first, then macOS's preferred languages, else English."""
    env = os.environ if env is None else env
    for var in ("LC_ALL", "LC_MESSAGES", "LANG"):
        code = (env.get(var) or "")[:2].lower()
        if code in LANGUAGES:
            return code
    try:
        out = run(["defaults", "read", "-g", "AppleLanguages"], capture_output=True, text=True).stdout
        for part in out.replace("(", " ").replace(")", " ").replace(",", " ").replace('"', " ").split():
            if part[:2].lower() in LANGUAGES:
                return part[:2].lower()
    except OSError:
        pass
    code = (locale.getlocale()[0] or "")[:2].lower()
    return code if code in LANGUAGES else "en"


def language(setting: str) -> str:
    return setting if setting in LANGUAGES else detect()


def t(lang: str, text_key: str, /, **values) -> str:
    return TEXTS.get(lang, TEXTS["en"]).get(text_key, TEXTS["en"][text_key]).format(**values)
